In [1]:
import numpy as np

In [3]:
data = np.random.randn(2,3) #shape가 [2,3] 인 배열객체를 가우시안 표준정규 분포에서의 랜덤값으로 초기화
print(data)

[[1.01735266 2.13342328 0.89816666]
 [0.51536739 1.94778339 0.11904835]]


In [5]:
print(data*10) #data의 모든 행렬에 10을 곱함

[[10.17352664 21.33423285  8.98166664]
 [ 5.15367392 19.47783389  1.19048354]]


In [7]:
print(data+data) #행렬덧셈

[[2.03470533 4.26684657 1.79633333]
 [1.03073478 3.89556678 0.23809671]]


In [10]:
print(data.shape) # shape
print(data.dtype) # type

(2, 3)
float64
